# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
version = "Two"
reorder_impl_items = true
use_field_init_shorthand = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
max_width = 80
